services:
  zabbix-proxy:
    container_name: "zabbix-proxy"
    image: zabbix/zabbix-proxy-sqlite3:7.0-ubuntu-latest
    pull_policy: always
    environment:
      - ZBX_PROXYMODE=0  # 0 - active proxy and 1 - passive proxy
      - ZBX_SERVER_HOST=192.168.0.235;192.168.0.236 #IP DOS ZABBIX SERVER
      - ZBX_SERVER_PORT=10051 #PORTA UTILIZADA 
      - ZBX_HOSTNAME=zbx7-proxy01 #NOME DO SEU PROXY
      - ZBX_DEBUGLEVEL=3  # 0 - basic info, 1 - critical, 2 - error, 3 - warning                                                                                                                                                             s, 4 - for debugging, 5 - extended debugging
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_PROXYLOCALBUFFER=0  # mantém cópia dos eventos mesmo depois de envia                                                                                                                                                             r ao server (valor em horas)
      - ZBX_PROXYOFFLINEBUFFER=1  # 6 horas
      - ZBX_PROXYHEARTBEATFREQUENCY=60  # 60 seg
      - ZBX_PROXYCONFIGFREQUENCY=200
      - ZBX_DATASENDERFREQUENCY=1  # 1 Seg
      - ZBX_STARTHISTORYPOLLERS=2  # ----------------
      - ZBX_STARTPOLLERS=10 #500
      - ZBX_STARTPREPROCESSORS=20 #500
      - ZBX_STARTPOLLERSUNREACHABLE=10   #300
      - ZBX_STARTPINGERS=10  #100
      - ZBX_STARTDISCOVERERS=5
      - ZBX_STARTHTTPPOLLERS=5
      - ZBX_HOUSEKEEPINGFREQUENCY=1
      - ZBX_STARTVMWARECOLLECTORS=1
      - ZBX_VMWAREFREQUENCY=60
      - ZBX_VMWAREPERFFREQUENCY=60
      - ZBX_VMWARECACHESIZE=32M
      - ZBX_VMWARETIMEOUT=300
      - ZBX_CACHESIZE=32M
      - ZBX_STARTDBSYNCERS=10 #20
      - ZBX_HISTORYCACHESIZE=32M
      - ZBX_HISTORYINDEXCACHESIZE=32M
      - ZBX_TIMEOUT=30  # 30 Seg
      - ZBX_UNREACHABLEPERIOD=10
      - ZBX_UNAVAILABLEDELAY=10
      - ZBX_UNREACHABLEDELAY=10
      - ZBX_LOGSLOWQUERIES=3000
      - ZBX_STATSALLOWEDIP=127.0.0.1
      - ZBX_TLSCONNECT=psk
      - ZBX_TLSACCEPT=psk
      - ZBX_TLSPSKIDENTITY=zbx7-proxy01 #NOME DO SEU PROXY, EU GOSTO DE UTILIZAR NO IDENTIFICAR DE PSK DO PROXY
      - ZBX_TLSPSKFILE=zabbix_proxy.psk
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /zabbix-proxy/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:r                                                                                                                                                             o
      - /zabbix-proxy/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscr                                                                                                                                                             ipts:ro
      - /zabbix-proxy/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /zabbix-proxy/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro