services:
  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: some-zabbix-server-pgsql
    environment:
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    init: true
    restart: unless-stopped
    networks:
      - Zabbix
    ports:
      - 5432:5432

  zabbix-web-apache-pgsql:
    image: zabbix/zabbix-web-apache-pgsql:alpine-7.0-latest
    container_name: some-zabbix-web-apache-pgsql
    ports:
      - "8081:8080"
    environment:
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - ZBX_SERVER_HOST=some-zabbix-server-pgsql
      - PHP_TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
      - Zabbix

  postgres-server:
    container_name: postgres-server
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - Zabbix
  #volumes:
  #  - /custom/mount:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

networks:
  Zabbix:
    driver: bridge