services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network
    ports:
      - '8081:8080'
      - '50000:50000'

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
 